import { useCallback, useEffect, useRef, useState } from 'react';
import { Button, SearchField, Skeleton, Input, Label, TextField, Table, ToggleButton, ToggleButtonGroup } from '@heroui/react';
import { CaretLeft, CaretRight, Plus, Users } from '@phosphor-icons/react';
import { AuthError, type AuthClient } from '../lib/auth-client';
import { loadActiveMasters, type EmployeeInput, type EmployeePage, type ProvisioningOperation, type TemporaryCredential } from '../lib/employees';
import type { MasterRecord } from '../lib/master-data';
import { StatusBadge } from '../components/molecules/StatusBadge';
import { Notice } from '../components/molecules/Notice';
import { ConfirmDialog } from '../components/organisms/ConfirmDialog';
import { EmployeeForm } from '../components/organisms/EmployeeForm';
import { TemporaryPasswordDialog } from '../components/organisms/TemporaryPasswordDialog';
const message = (error: unknown) => error instanceof Error ? error.message : 'Terjadi kesalahan. Coba lagi.';
export function EmployeesPage({ client, params, onParamsChange, onSessionExpired }: { client: Pick<AuthClient, 'api'>; params: URLSearchParams; onParamsChange: (next: Record<string, string | undefined>) => void; onSessionExpired: () => void }) {
  const search = params.get('search') ?? ''; const status = ['ACTIVE', 'INACTIVE'].includes(params.get('status') ?? '') ? params.get('status')! : 'ALL'; const page = Math.max(1, Number(params.get('page')) || 1);
  const operationId = params.get('operation') ?? '';
  const [data, setData] = useState<EmployeePage | null>(null); const [query, setQuery] = useState(search); const listKey = search + '|' + status + '|' + page; const [loadedKey, setLoadedKey] = useState(''); const [reload, setReload] = useState(0);
  const [error, setError] = useState(''); const [loadError, setLoadError] = useState(''); const [formError, setFormError] = useState(''); const [notice, setNotice] = useState(''); const [busy, setBusy] = useState(false);
  const [form, setForm] = useState(false); const [masters, setMasters] = useState<{ departments: MasterRecord[]; positions: MasterRecord[] } | null>(null); const [masterError, setMasterError] = useState('');
  const [operationState, setOperation] = useState<ProvisioningOperation | null>(null); const [credential, setCredential] = useState<TemporaryCredential | null>(null); const [recover, setRecover] = useState(false); const [correctedEmail, setCorrectedEmail] = useState('');
  const operation = operationState?.id === operationId ? operationState : null;
  const loading = loadedKey !== listKey + '|' + reload;
  const submission = useRef<{ key: string; payload: string } | null>(null);
  const handle = useCallback((reason: unknown) => { if (reason instanceof AuthError && reason.status === 401) onSessionExpired(); return message(reason); }, [onSessionExpired]);
  const filters = useCallback((next: Record<string, string | undefined>) => onParamsChange({ search: search || undefined, status: status === 'ALL' ? undefined : status, page: page > 1 ? String(page) : undefined, operation: operationId || undefined, ...next }), [onParamsChange, operationId, page, search, status]);
  useEffect(() => { let active = true; const qs = new URLSearchParams({ page: String(page), pageSize: '20' }); if (search) qs.set('search', search); if (status !== 'ALL') qs.set('status', status);
    client.api<EmployeePage>('employees?' + qs).then(value => { if (active) { setData(value); setLoadError(''); } }).catch((reason: unknown) => { if (active) setLoadError(handle(reason)); }).finally(() => { if (active) setLoadedKey(listKey + '|' + reload); }); return () => { active = false; };
  }, [client, handle, listKey, page, reload, search, status]);
  useEffect(() => { if (query.trim() === search) return; const timer = setTimeout(() => filters({ search: query.trim() || undefined, page: undefined }), 300); return () => clearTimeout(timer); }, [filters, query, search]);
  useEffect(() => { if (!form) return; let active = true; Promise.all([loadActiveMasters(client, 'departments'), loadActiveMasters(client, 'positions')]).then(([departments, positions]) => { if (active) setMasters({ departments, positions }); }).catch((reason: unknown) => { if (active) setMasterError(handle(reason)); }); return () => { active = false; }; }, [client, form, handle, reload]);
  useEffect(() => { if (!operationId) return; let active = true; let timer: ReturnType<typeof setTimeout> | undefined;
    async function poll() { try { const value = await client.api<ProvisioningOperation>('employee-provisioning/' + operationId); if (!active) return; setOperation(value); if (value.status === 'PENDING') timer = setTimeout(() => void poll(), 2000); else setReload(value => value + 1); } catch (reason) { if (active) setError(handle(reason)); } }
    void poll(); return () => { active = false; if (timer) clearTimeout(timer); };
  }, [client, handle, operationId]);
  async function claim(id: string, replacement = false) { setBusy(true); setError(''); try { const value = await client.api<TemporaryCredential>('employee-provisioning/' + id + '/credentials', { method: 'POST', body: replacement ? { recover: true } : {} }); setCredential(value); setRecover(false); } catch (reason) { setError(handle(reason)); } finally { setBusy(false); } }
  async function create(input: EmployeeInput) {
    const payload = JSON.stringify(input); if (!submission.current || submission.current.payload !== payload) submission.current = { key: crypto.randomUUID(), payload };
    const key = submission.current.key; setBusy(true); setFormError(''); setError('');
    try { const value = await client.api<ProvisioningOperation>('employees', { method: 'POST', body: input, idempotencyKey: key }); setOperation(value); setForm(false); filters({ operation: value.id }); setReload(value => value + 1); if (value.status === 'COMPLETED') await claim(value.id); }
    catch (reason) {
      setFormError(handle(reason));
      // Resolve an ambiguous create response using the same key rather than submitting a second account.
      try { const value = await client.api<ProvisioningOperation>('employee-provisioning/' + key); setOperation(value); setForm(false); filters({ operation: key }); } catch { /* A validation/unique failure may have created no operation. Keep the form and key for an explicit retry. */ }
    } finally { setBusy(false); }
  }
  async function retry(email?: string) { if (!operation) return; setBusy(true); setError(''); try { const value = await client.api<ProvisioningOperation>('employee-provisioning/' + operation.id + '/retry', { method: 'POST', body: email ? { email } : {} }); setOperation(value); setReload(value => value + 1); if (value.status === 'COMPLETED') await claim(value.id); } catch (reason) { setError(handle(reason)); } finally { setBusy(false); } }
  const open = () => { setMasters(null); setMasterError(''); setFormError(''); setNotice(''); setForm(true); submission.current = null; };
  const total = data?.total ?? 0; const last = Math.max(1, Math.ceil(total / 20));
  return <div className="list-page">
    {notice && !operationId && <Notice message={notice} success />}{loadError && <div className="load-error"><Notice message={loadError} /><Button size="sm" variant="secondary" onPress={() => setReload(value => value + 1)}>Coba lagi</Button></div>}{error && !recover && <div className="load-error"><Notice message={error} /><Button size="sm" variant="secondary" onPress={() => setReload(value => value + 1)}>Coba lagi</Button></div>}
    {operation && !credential && <div className="provisioning-result" aria-live="polite"><p className="cell-strong">{operation.status === 'COMPLETED' ? 'Profil dan akun selesai dibuat' : operation.status === 'FAILED' ? 'Pembuatan akun perlu diperiksa' : 'Menyiapkan profil dan akun'}</p><p className="dialog-text">{operation.email}{operation.errorCode === 'EMAIL_CONFLICT' ? ': email sudah digunakan. NIK tetap dicadangkan; akun kedua tidak dibuat.' : operation.status === 'PENDING' ? '. Anda dapat menunggu atau mencoba melanjutkan.' : ''}</p><div className="form-actions">{operation.status === 'COMPLETED' ? <><Button variant="primary" isDisabled={busy} onPress={() => void claim(operation.id)}>Tampilkan password</Button><Button variant="secondary" isDisabled={busy} onPress={() => setRecover(true)}>Buat pengganti</Button></> : operation.canCorrectEmail ? <><TextField className="form-field" type="email" value={correctedEmail} onChange={setCorrectedEmail} isDisabled={busy}><Label>Email pengganti</Label><Input /></TextField><Button variant="primary" isDisabled={busy || !correctedEmail.trim()} onPress={() => void retry(correctedEmail.trim())}>Perbaiki email</Button></> : operation.errorCode !== 'EMAIL_CONFLICT' && <Button variant="secondary" isDisabled={busy} onPress={() => void retry()}>Lanjutkan pembuatan</Button>}</div></div>}
    {form ? <><div className="employee-form-heading"><h2>Tambah karyawan</h2></div>{masterError ? <div className="load-error"><Notice message={masterError} /><Button variant="secondary" onPress={() => { setMasters(null); setMasterError(''); setReload(value => value + 1); }}>Muat pilihan lagi</Button><Button variant="tertiary" onPress={() => setForm(false)}>Batal</Button></div> : !masters ? <p role="status">Memuat pilihan departemen dan jabatan…</p> : <EmployeeForm departments={masters.departments} positions={masters.positions} busy={busy} error={formError} onSubmit={input => void create(input)} onCancel={() => setForm(false)} />}</> : <>
      <div className="list-toolbar" role="search"><SearchField className="list-search" value={query} onChange={setQuery} aria-label="Cari karyawan"><SearchField.Group><SearchField.SearchIcon /><SearchField.Input placeholder="Cari nama atau NIK" /><SearchField.ClearButton /></SearchField.Group></SearchField><ToggleButtonGroup className="status-filter" aria-label="Filter status" selectionMode="single" disallowEmptySelection selectedKeys={[status]} onSelectionChange={keys => { const [key] = [...keys]; if (key) filters({ status: key === 'ALL' ? undefined : String(key), page: undefined }); }}><ToggleButton id="ALL">Semua</ToggleButton><ToggleButton id="ACTIVE"><ToggleButtonGroup.Separator />Aktif</ToggleButton><ToggleButton id="INACTIVE"><ToggleButtonGroup.Separator />Nonaktif</ToggleButton></ToggleButtonGroup><Button variant="primary" className="list-add" isDisabled={busy || operation?.status === 'PENDING'} onPress={open}><Plus size={16} aria-hidden="true" />Tambah</Button></div>
      {loading ? <div className="table-skeleton" aria-label="Memuat karyawan">{[0,1,2].map(value => <Skeleton className="skeleton-row" key={value} />)}</div> : !loadError && !data?.items.length ? <div className="empty-state"><span className="empty-icon" aria-hidden="true"><Users size={22} /></span><p className="empty-title">{search || status !== 'ALL' ? 'Tidak ada karyawan yang cocok' : 'Belum ada karyawan'}</p><p className="empty-body">{search || status !== 'ALL' ? 'Ubah kata kunci atau status pencarian.' : 'Tambahkan profil dan akun karyawan pertama.'}</p>{search || status !== 'ALL' ? <Button variant="secondary" onPress={() => { setQuery(''); filters({ search: undefined, status: undefined, page: undefined }); }}>Bersihkan filter</Button> : <Button variant="primary" onPress={open}>Tambah karyawan</Button>}</div> : !loadError && data?.items.length ? <><Table className="data-table employee-table"><Table.ScrollContainer><Table.Content aria-label="Daftar karyawan" className="employee-table-content"><Table.Header><Table.Column isRowHeader>Karyawan</Table.Column><Table.Column>Penugasan</Table.Column><Table.Column>Status</Table.Column></Table.Header><Table.Body>{data.items.map(row => <Table.Row id={row.id} key={row.id}><Table.Cell><span className="cell-strong">{row.name}</span><span className="employee-secondary">{row.nik}</span><span className="employee-secondary employee-extra">{row.email}</span></Table.Cell><Table.Cell>{row.department}<span className="employee-secondary">{row.position}</span></Table.Cell><Table.Cell><StatusBadge status={row.status} /></Table.Cell></Table.Row>)}</Table.Body></Table.Content></Table.ScrollContainer></Table><nav className="list-pager" aria-label="Halaman karyawan"><span className="list-pager-range">{total ? (page - 1) * 20 + 1 : 0}-{Math.min(page * 20,total)} dari {total}</span><div className="list-pager-buttons"><Button variant="secondary" size="sm" isIconOnly aria-label="Halaman sebelumnya" isDisabled={page <= 1} onPress={() => filters({ page: page - 1 > 1 ? String(page - 1) : undefined })}><CaretLeft size={16} /></Button><Button variant="secondary" size="sm" isIconOnly aria-label="Halaman berikutnya" isDisabled={page >= last} onPress={() => filters({ page: String(page + 1) })}><CaretRight size={16} /></Button></div></nav></> : null}
    </>}
    {credential && <TemporaryPasswordDialog credential={credential} onClose={() => { setCredential(null); setOperation(null); filters({ operation: undefined }); setNotice('Karyawan berhasil dibuat. Password sementara telah ditutup.'); }} />}
    <ConfirmDialog open={recover} title="Buat password pengganti?" confirmLabel="Buat pengganti" busy={busy} error={error} onClose={() => setRecover(false)} onConfirm={() => operation && void claim(operation.id, true)}><p className="dialog-text">Gunakan jika respons password sebelumnya hilang. Password sementara dan sesi lama dibatalkan. Tindakan hanya tersedia sebelum karyawan mengganti password pertama.</p></ConfirmDialog>
  </div>;
}
